### ISSUE TITLE
Red/Yellow pawns can jump over other pieces

### ISSUE THREAD

**Issue by DankRank** [johnnyvf24/hellochess-v2#4]
To reproduce this issue, play as either red or yellow, and move one of your knights out, and then try to move the pawn two cells forward, jumping over the knight, as in the following screenshot.
![image](https://cloud.githubusercontent.com/assets/4050457/26605765/ecdf97ee-4597-11e7-8884-022a962b4ec0.png)

Note that this doesn't work with white/black.

**Comment by johnnyvf24** [comment]
Fixed. Thanks for bringing this up! :)

**Comment by johnnyvf24** [comment]
Fixed. Thanks for bringing this up! :)

**Comment by johnnyvf24** [comment]
Fixed. Thanks for bringing this up! :)
